<a href="https://colab.research.google.com/github/RashikaTyagi01/Rashika-UCS420/blob/main/cognitiveAssignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q.1** Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [ ]:
import numpy as np
a = np.array([1,2,4,6,8])

for i in range(0,5):
  a[i]+=2
print(a)

for i in range(0,5):
  a[i]*=3
print(a)

for i in range(0,5):
  a[i]/=2
print(a)

[ 3  4  6  8 10]
[ 9 12 18 24 30]
[ 4  6  9 12 15]


**Q.2** Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [ ]:
import numpy as np
a = np.array([1,2,3,6,4,5])
result = np.flip(a)
print(result)

[5 4 6 3 2 1]


b) Find the most frequent value and their indice(s) in the following arrays:
i) x = np.array([1,2,3,4,5,1,2,1,1,1])


In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
mostFreq = np.bincount(x).argmax()
print("The most frequent value: ",mostFreq)
print("The indices of most frequent value: ",np.where(x==mostFreq)[0])

The most frequent value:  1
The indices of most frequent value:  [0 5 7 8 9]


b)ii)  y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
mostFreq=np.bincount(y).argmax()
print("The most frequent value: ",mostFreq)
print("The indices of most frequent value: ",np.where(y==mostFreq)[0])

The most frequent value:  1
The indices of most frequent value:  [0 1 2]


**Q.3** For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [ ]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0][1])
print(arr[2][0])

20
70


**Q.4** Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [9]:
import numpy as np
rashika = np.linspace(10,100,25)
print(rashika)
print("The dimension of array: ",rashika.ndim)
print("Shape of array: ",rashika.shape)
print("Size of array: ",rashika.size)
print("DataType: ",rashika.dtype)
print("Total number of bytes consumed by the array: ",rashika.nbytes)

transpose = rashika.reshape(-1,1)
print(transpose)

rT = rashika.T
print(rT)
#cannot do the same with T attribute

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
The dimension of array:  1
Shape of array:  (25,)
Size of array:  25
DataType:  float64
Total number of bytes consumed by the array:  200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


**Q.5** Create a 2-D Array of three rows and four columns, named ucs420_<yourname>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [8]:
import numpy as np
ucs420_Rashika = np.array([[10,20,30,40], [50,60,70,80], [90,15,20,35]])
print("The mean: ", np.mean(ucs420_Rashika))
print("The median: ",np.median(ucs420_Rashika))
print("The max: ",ucs420_Rashika.max())
print("The min: ", ucs420_Rashika.min())
print("The unique elements: ", np.unique(ucs420_Rashika))

reshaped_ucs420_Rashika = ucs420_Rashika.reshape(4,3)
print("The reshaped array: ")
print(reshaped_ucs420_Rashika)

resized_ucs420_Rashika = np.resize(ucs420_Rashika,(2,3))
print("The resized array: ")
print(resized_ucs420_Rashika)

The mean:  43.333333333333336
The median:  37.5
The max:  90
The min:  10
The unique elements:  [10 15 20 30 35 40 50 60 70 80 90]
The reshaped array: 
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
The resized array: 
[[10 20 30]
 [40 50 60]]
